/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jerinphilip_slimt_Model */

#ifndef _Included_com_github_jerinphilip_slimt_Model
#define _Included_com_github_jerinphilip_slimt_Model
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jerinphilip_slimt_Model
 * Method:    Model_createModel
 * Signature: (Lcom/github/jerinphilip/slimt/ModelConfig;Lcom/github/jerinphilip/slimt/Package;)J
 */
JNIEXPORT jlong JNICALL Java_com_github_jerinphilip_slimt_Model_Model_1createModel
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_github_jerinphilip_slimt_Model
 * Method:    Model_destroyModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_jerinphilip_slimt_Model_Model_1destroyModel
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
